- name: Install Caddy
  shell: |
    apt install -y debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
    apt update
    apt install caddy -y
  args:
    executable: /bin/bash

- name: Configure Caddy reverse proxy
  copy:
    dest: /etc/caddy/Caddyfile
    content: |
      chat.example.com {
          reverse_proxy localhost:8065
          tls you@example.com
      }

- name: Restart Caddy
  systemd:
    name: caddy
    enabled: yes
    state: restarted
