- name: Update APT cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - curl
      - wget
      - unzip
      - gnupg2
      - software-properties-common
      - ufw
    state: present
