- name: Install Coturn
  apt:
    name: coturn
    state: present

- name: Configure Coturn
  copy:
    dest: /etc/turnserver.conf
    content: |
      listening-port=3478
      tls-listening-port=5349
      realm=turn.example.com
      user=turnuser:turnpassword
      fingerprint
      lt-cred-mech
      use-auth-secret
      static-auth-secret=supersecret
      total-quota=100
      bps-capacity=0
      stale-nonce
      cert=/etc/ssl/certs/ssl-cert-snakeoil.pem
      pkey=/etc/ssl/private/ssl-cert-snakeoil.key
      no-multicast-peers
      no-loopback-peers

- name: Enable and start Coturn
  systemd:
    name: coturn
    enabled: yes
    state: started
